### ISSUE TITLE
Question about Language-Level Benchmark

### ISSUE THREAD

**Issue by MozerWang** [wcx21/Social-Tasks-in-Sandbox-Simulation#1]
Great work! I have some questions about the Language-Level Benchmark：

Is this an open-end setting benchmark? All we have to do is follow the settings, simulate the conversation, and evaluate the content of the conversation, right?

**Comment by wcx21** [comment]
Sorry for the late reply. Yes, you can run the simulation and evaluate the conversations by following the instructions. And you can also customize new tasks.
